### ISSUE TITLE
OpenVPN provisioning fails on Redhat

### ISSUE THREAD

**Issue by adam-sandor** [ContainerSolutions/terraform-mesos#49] opened 2016-07-14 10:24 UTC
Provisioning with Redhat VM fails on missing configuration file while provisioning OpenVPN on the master node.

```
module.mesos.google_compute_instance.mesos-master (remote-exec): sed: can't read /etc/sysctl.d/11-gce-network-security.conf: No such file or directory
```

My configuration is:

``` tf
module "mesos" {
  source = "github.com/ContainerSolutions/terraform-mesos"
  account_file = "/Users/asandor/Projects/cs/infraloop/credentials/gcloud-service-account.json"
  project = "cs-cisco"
  region = "europe-west1"
  zone = "europe-west1-d"
  gce_ssh_user = "asandor"
  gce_ssh_private_key_file = "/Users/asandor/.ssh/google_compute_engine"
  name = "infraloop-mesos-dev"
  masters = "1"
  slaves = "2"
  subnetwork = "10.20.30.0/24"
  domain = "dev.mesos.infraloop.container-solutions.com"
  mesos_version = "0.28.2"
  image = "rhel-7-v20160418"
  distribution = "redhat"
  slave_machine_type = "n1-standard-2"
  # slave_resources             = "cpus(*):0.90; disk(*):7128"
}
```

**Comment by thijsschnitger** [comment] 2016-07-14 11:32
put the ip_forward statement in /etc/sysctl.conf

**Comment by frankscholten** [comment] 2016-07-20 09:48
@thijsschnitger 

This line already sets `ip_forward`. https://github.com/ContainerSolutions/terraform-mesos/blob/59968fa748a5cb12103a3de70096ae95ec59d9d3/scripts/openvpn_install_ubuntu.sh#L27

For IPv4 at least.

**Comment by frankscholten** [comment] 2016-07-20 09:54
Ah so the problem is that the config file is not in `/etc/sysctl.d/11-gce-network-security.conf` in RedHat.

**Comment by frankscholten** [comment] 2016-07-26 11:21
Fixed by https://github.com/ContainerSolutions/terraform-mesos/pull/50

**Closed as completed by frankscholten** 2016-07-26 11:21 UTC
Labels: bug
